version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql