CREATE TABLE devices {
    id INT PRIMARY KEY AUTO_INCREMENT,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE users {
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
}

CREATE TABLE temperature {
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT NOT NULL,
    `data` FLOAT NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
}

CREATE TABLE fall_detection {
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
}

CREATE TABLE panic_alert {
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
}

CREATE TABLE oxymetry {
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT NOT NULL,
    `data` FLOAT NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
}

CREATE TABLE heart_rate {
    id INT PRIMARY KEY AUTO_INCREMENT,
    device_id INT NOT NULL,
    `data` FLOAT NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
}